@startuml

' Classes to represent various components of an HTTP request
class HTTPRequest {
    url
    method
}

class Header {
}

class Parameter {
    name
    in
    required
    schema
}

class RequestBody{
    content
    schema
}


class Schema {
}

class Name{
}

class Format{
}

class Atributte{
 type
 name
 value
 Is_id
}
class Object{

}


HTTPRequest "1" -- "1..*" Header : contains >
HTTPRequest "1" -- "1" Parameter : has >
HTTPRequest "1" -- "1" Schema : needs  >
HTTPRequest "1" -- "1" RequestBody : has >
Schema "1" -- "1..*" Object: is composed by  >

Atributte "1" -- "1" Format : has >
Schema "1" -- "1" Name : has >
Object "1" -- "1..*" Atributte : has >


@enduml
